on: [push]
jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: setup-java8
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '8'
            cache: maven
      - run: mvn -version
      - run: mvn --batch-mode --update-snapshots verify
      - name: Archive integration test build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: it-logs
          retention-days: 5
          path: /home/runner/work/acosix-maven-parent/acosix-maven-parent/*/target/its/*/build.log
